# -*- coding=utf-8 -*- 
jqzx = [
   ("94页论文综述卷积神经网络：从基础技术到研究前景","https://www.jiqizhixin.com/articles/2018-04-07-4"),
   ("ASSIA | 中国自动化学会“深度与宽度强化学习”前沿讲习班","https://www.jiqizhixin.com/articles/ASSIA"),
   ("AlphaGo Zero：笔记与伪代码","https://www.jiqizhixin.com/articles/2017-11-02-18"),
   ("MXNet开放支持Keras，高效实现CNN与RNN的分布式训练今日 AWS 发布博客宣布 Apache MXNet 已经支持 Keras 2，开发者可以使用 Keras-MXNet 深度学习后端进行 CNN 和 RNN 的训练，安装简便，速度提升，同时支持保存 MXNet 模型。","https://www.jiqizhixin.com/articles/2018-05-22-11"),
   ("Python扩大领先优势，PyTorch仅占6.4%：2018年数据科学语言&工具排名著名数据科学网站 KDnuggets 发布了 2018 年数据科学和机器学习工具调查结果","https://www.jiqizhixin.com/articles/2018-05-23-7"),
   ("Tools for AI：以开发者为中心的全平台人工智能开发套件微软围绕“如何利用人工智能技术来构建更智能的云和边缘计算”这个中心，介绍了从Cognitive Services、Bot Framework、 Azure ML到Brainwave等一系列产品更新。","https://www.jiqizhixin.com/articles/2018-05-22-3"),
   ("Zero to Hero：2017年机器之心AI高分概述文章全集","https://www.jiqizhixin.com/articles/Zero-to-Hero-2017-synced-overview-articles-collection"),
   ("「俩披萨能喂饱的团队才是好团队」，细数贝索斯建立商业帝国的决策方法论","https://www.jiqizhixin.com/articles/2018-05-02-6"),
   ("「分段映射」帮助利用少量样本习得新类别细粒度分类器近日，来自南京大学、旷视和阿德莱德大学的研究者在 arXiv 上发布论文，提出一种利用少量样本学习新类别细粒度分类器的新方法 FSFG 模型。","https://www.jiqizhixin.com/articles/2018-05-22-8"),
   ("一文简述多种无监督聚类算法的Python实现本文简要介绍了多种无监督学习算法的 Python 实现，包括 K 均值聚类、层次聚类、t-SNE 聚类、DBSCAN 聚类。","https://www.jiqizhixin.com/articles/2018-05-22-10"),
   ("与模型无关的元学习，UC Berkeley提出一种可推广到各类任务的元学习方法","https://www.jiqizhixin.com/articles/2017-07-20-4"),
   ("从DensNet到CliqueNet，解读北大在卷积架构上的探索微软亚洲研究院主办了一场关于 CVPR 2018 中国论文分享会，机器之心在分享会中发现了一篇非常有意思的论文","https://www.jiqizhixin.com/articles/2018-05-23-6"),
   ("从入门到高阶，读懂机器学习需要哪些数学知识（附网盘）","https://www.jiqizhixin.com/articles/2018-04-12-4"),
   ("伯克利最新研究：用算法解决算法偏差？公平机器学习的延迟影响这篇文章的主要目标，是基于社会福利的长期目标对机器学习的决策进行了调整。","https://www.jiqizhixin.com/articles/2018-05-23-8"),
   ("关于知识图谱，各路大神最近都在读哪些论文？「知识图谱」专题论文笔记分享~","https://www.jiqizhixin.com/articles/2018-05-23-10"),
   ("助力医疗，聚焦AI——“人工智能卓医创新挑战赛”火热开赛组委会诚邀国内外对人工智能医疗领域怀有理想的人士报名参赛！","https://www.jiqizhixin.com/articles/MedSci"),
   ("卷积神经网络可视化：以Keras处理猫图片为例","https://www.jiqizhixin.com/articles/2017-02-16-3"),
   ("又快又准确，新目标检测器速度可达每秒200帧爱尔兰联合技术研究中心介绍了他们在保证准确度的同时达到了 200 FPS 速度的目标检测研究进展","https://www.jiqizhixin.com/articles/2018-05-23-5"),
   ("基于注意力机制，机器之心带你理解与训练神经机器翻译系统","https://www.jiqizhixin.com/articles/Synced-github-implement-project-machine-translation-by-transformer"),
   ("奇式维新，百度迷途改革未完成的百度，在陆奇走后，是否会继续正视自己的问题。我们要讨论的不是陆奇，而是从策略层面分析百度两大 AI 应用平台存在的困境。","https://www.jiqizhixin.com/articles/2018-05-22"),
   ("快手AR变脸爆红的坚实后盾：自研3D引擎与AI技术平台AR尬脸舞是怎样炼成的？","https://www.jiqizhixin.com/articles/kuaishou"),
   ("惹争议！本科毕业生成为NIPS 2018论文同行评审","https://www.jiqizhixin.com/articles/nips2018-undergraduate-peer-reviewers-controversy"),
   ("机器之心GitHub项目：从循环到卷积，探索序列建模的奥秘","https://www.jiqizhixin.com/articles/2018-04-12-3"),
   ("海康、UCLA、北理联合提出3D DescriptorNet：可按条件生成3D形状，克服模式崩溃","https://www.jiqizhixin.com/articles/2018-04-11"),
   ("独角兽奥比中光融资2亿美元背后，是暗潮汹涌的3D摄像头江湖目前，在消费电子领域，尤其是手机领域，传统摄像头公司建立的供应链壁垒很难被打破，3D 摄像头创业公司需要将目光投向新型智能硬件载体。","https://www.jiqizhixin.com/articles/2018-05-22-2"),
   ("猎豹移动Q1利润与利润率持续增长 未来开发更多实用且易用机器人产品北京时间5月21日，全球领先的移动互联网公司猎豹移动（NYSE: CMCM）发布了截至2018年3月31日的第一季度财报。","https://www.jiqizhixin.com/articles/2018-05-22-16"),
   ("百度AI开发者实战营成都站","http://www.huodongxing.com/event/5437894683500?qd=jiqizhixin"),
   ("百度高级副总裁向海龙：依托AI，全面拥抱视频时代百度依托AI能力，全面拥抱视频时代。","https://www.jiqizhixin.com/articles/052201"),
   ("英国最大医院之一UCLH将采用AI提升医疗服务效率从癌症诊断到减少候诊时间，UCLH 旨在将人工智能「革命性」的功效带给 NHS 患者。","https://www.jiqizhixin.com/articles/2018-05-23"),
   ("蚂蚁人工智能大赛","https://dc.cloud.alipay.com/index#/home"),
   ("计算机视觉工具包Luminoth今日开源","https://www.jiqizhixin.com/articles/2017-10-11-6"),
   ("谷歌如何利用人工智能重塑美国医疗行业？谷歌正利用 AI 进军医疗领域","https://www.jiqizhixin.com/articles/2018-05-23-2"),
   ("谷歌机器学习43条规则：机器学习工程的最佳实践经验谷歌分享 43 条机器学习工程的最佳实践开发经验。","https://www.jiqizhixin.com/articles/2018-05-22-12"),
   ("重新定义美国的伟大：Watson与IBM超过半个世纪的发展历程「伟大」是复杂的，随着时间的推移，我们对「伟大」的定义也发生了变化。","https://www.jiqizhixin.com/articles/2018-05-23-9"),
   ("阿里发布业务平台解决方案 预计3年内将帮助业务提升10倍效率如何让产品经理和开发工程师和睦相处？阿里程序员动手打造了一个“灭霸宝石套餐”","https://www.jiqizhixin.com/articles/2018-05-23-4"),
   ("阿里国际化展现翻译AI价值，达摩院获WMT机器翻译大赛5项冠军在刚刚结束的 WMT2018 国际机器翻译大赛上，阿里巴巴达摩院机器智能-NLP 翻译团队在所有提交的 5 项比赛中全数获得冠军，这 5 个项目分别是英文-中文翻译、英文-俄罗斯语互译、英文-土耳其语互译。","https://www.jiqizhixin.com/articles/2018-05-24"),
   ("为什么机器学习在投资领域不好使关注有趣的事件与弄清楚哪些事件是有趣的是两码事，这就是数据迁就的本质。","https://www.jiqizhixin.com/articles/2018-05-03-11"),
   ("提升用户幸福感：快手在AI技术上的探索与应用在短视频社交快速发展的背后，快手应用了很多人工智能技术。","https://www.jiqizhixin.com/articles/kuaishou-ai-exploration"),
   ("让问答模型真正理解问题：归因分析轻松构造对抗问题样本研究者们通过归因方法分析了三种深度学习问答模型的内在过程，包括了对图像、图表和文本段落的问答。","https://www.jiqizhixin.com/articles/Did-the-Model-Understand-the-Question"),
   ("工业物联网行情见长，力推工业云平台的老牌公司西门子如何「挥拳」出击？| 对话对于西门子来说，人工智能既是一个让人兴奋的课题，又是一个富有极高要求的工作内容。","https://www.jiqizhixin.com/articles/2018-05-23-13"),
   ("最以客户为中心？亚马逊人脸识别技术正被警方用于监控人群30 万张嫌疑犯照片的数据库，和一个专为警察们提供人脸参照的手机应用程序。而且，亚马逊还在怂恿该县招来其他潜在客户服务。","https://www.jiqizhixin.com/articles/2018-05-23-12"),
   ("运筹学发展概况（上）运筹学历史回顾和发展概论，本篇文章为上篇。","https://www.jiqizhixin.com/articles/2018-05-12"),
]
